name = "love-story"
account_id = "YOUR_ACCOUNT_ID" # 替换为您的Cloudflare账户ID
workers_dev = true
compatibility_date = "2023-10-08"
main = "next-app/simple-worker.js"

[vars]
# 在这里添加环境变量
# ADMIN_USERNAME = "admin"
# ADMIN_PASSWORD_HASH = "hashed_password"

# 启用模块语法
nodejs_compat = true